name: Go

on:
  pull_request:
    branches: [main]

jobs:
  Automated-classdiagrams-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Go plantuml parse
        run: go get github.com/jfeliu007/goplantuml/parser

      - name: Get Go plantuml
        run: go install github.com/jfeliu007/goplantuml/cmd/goplantuml@latest

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore: refresh files"
          branch: master

      - name: Test
        run: |
          touch demo.puml
          goplantuml -recursive ./plantuml > ./demo.puml

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore: refresh files"
          branch: main

      - name: Commit log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout main
          git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"
